// Barrel export for all shared types.
// Import from "@/engines/shared/types" instead of individual files.

export type {
  DegreeLevel,
  RiskLevel,
  RoleClass,
  ProjectComplexity,
  OwnershipLevel,
  ProjectSource,
  AudienceScope,
  ProficiencyLevel,
  SeniorityLevel,
  RoleFamily,
  CandidateArchetype,
  DocumentQuality,
  ResumeQuality,
  EvidenceStrength,
  CareerConsistency,
  WorkModePreference,
  RelocationWillingness,
  EmploymentStatus,
  CommunicationTier,
  DomainPosture,
  CareerDirection,
  CareerVelocity,
  SourceFormat,
  ContributionType,
  CompensationPeriod,
} from "./enums";

export type {
  RoleEntry,
  LeadershipSignals,
  OwnershipSignals,
  Project,
  Achievement,
  Publication,
  OpenSourceContribution,
  Certification,
  SpokenLanguage,
  Presentation,
  TechnicalWriting,
  MentoringSignals,
  CommunitySignals,
  CommunicationSignals,
  CompensationExpectation,
  CareerPreferences,
  RiskSignals,
  CareerTrajectory,
} from "./sub-types";

export type { CandidateProfile } from "./candidate-profile-v2";

export type {
  PreflightInput,
  QualitySignals,
  PreflightOutput,
  SectionMap,
  SectionDetectionOutput,
  FieldConfidence,
  IdentityOutput,
  UncertainSkill,
  SkillsOutput,
  ExperienceOutput,
  ProjectsOutput,
  EducationOutput,
  EvidenceOutput,
  CommunicationOutput,
  PreferencesOutput,
  QualityOutput,
  RiskOutput,
  RecruiterSignalsOutput,
  ArchetypeSummarySignals,
  ArchetypeOutput,
  AssemblyOutput,
  ValidationOutput,
  AllStageOutputs,
} from "./stage-outputs";
