"use client";

import { useRef, useState } from "react";
import Link from "next/link";
import { extractFromFile, ExtractionError } from "@/lib/extraction";
import {
  type AnalysisOutput,
  type GapItem,
  type StrengthItem,
  SAMPLE_ANALYSIS,
} from "@/lib/candidate-review-sample";
import UploadCard, { type UploadState } from "@/components/shared/UploadCard";
import {
  ScoreRing,
  verdictBadgeClass,
  severityClass,
  SpinnerIcon,
  DownloadIcon,
} from "@/components/shared/score-display";

// ── Helpers ───────────────────────────────────────────────────────────────────

// Short delay so the "Uploading…" phase is genuinely visible before the
// heavier "Extracting…" work begins.
function nextFrame(): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, 280));
}

function generateMarkdown(analysis: AnalysisOutput): string {
  const { overall_match_score: score, analysis_summary, strength_analysis, gap_analysis, recruiter_perspective: rp, improvement_roadmap: ir } = analysis;
  return [
    `# PeakMinds Candidate Review Report`,
    ``,
    `## Overall Match Score: ${score}/100`,
    ``,
    analysis_summary,
    ``,
    `## Strengths`,
    ...strength_analysis.map((s) => `### ${s.title}\n${s.description}`),
    ``,
    `## Gaps`,
    ...gap_analysis.map((g) => `### ${g.title} [${g.severity}]\n${g.description}`),
    ``,
    `## Recruiter Perspective`,
    `**Verdict:** ${rp.verdict}`,
    ``,
    `**Positives:**`,
    ...rp.positives.map((p) => `- ${p}`),
    ``,
    `**Concerns:**`,
    ...rp.concerns.map((c) => `- ${c}`),
    ``,
    `## Improvement Roadmap`,
    `### Immediate`,
    ...ir.immediate.map((i) => `- ${i}`),
    `### 7-Day Plan`,
    ...ir.seven_day.map((i) => `- ${i}`),
    `### 30-Day Plan`,
    ...ir.thirty_day.map((i) => `- ${i}`),
    ``,
    `---`,
    `Generated by PeakMinds Talent Intelligence Platform`,
  ].join("\n");
}

function downloadMarkdown(analysis: AnalysisOutput) {
  const md = generateMarkdown(analysis);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "peakminds-candidate-review.md";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// Generates a styled PDF report via lazy-loaded jspdf (no homepage bundle
// impact). Falls back to Markdown if PDF generation fails for any reason.
async function downloadReport(analysis: AnalysisOutput) {
  try {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF({ unit: "pt", format: "a4" });

    const PAGE_W = doc.internal.pageSize.getWidth();
    const PAGE_H = doc.internal.pageSize.getHeight();
    const MARGIN = 48;
    const MAX_W = PAGE_W - MARGIN * 2;
    let y = MARGIN;

    const ensureSpace = (needed: number) => {
      if (y + needed > PAGE_H - MARGIN) {
        doc.addPage();
        y = MARGIN;
      }
    };

    const writeWrapped = (text: string, size: number, opts?: { bold?: boolean; color?: [number, number, number]; gap?: number }) => {
      doc.setFont("helvetica", opts?.bold ? "bold" : "normal");
      doc.setFontSize(size);
      doc.setTextColor(...(opts?.color ?? [30, 30, 30]));
      const lines = doc.splitTextToSize(text, MAX_W) as string[];
      const lineH = size * 1.4;
      for (const line of lines) {
        ensureSpace(lineH);
        doc.text(line, MARGIN, y);
        y += lineH;
      }
      y += opts?.gap ?? 4;
    };

    const heading = (text: string) => {
      y += 8;
      ensureSpace(28);
      doc.setDrawColor(255, 77, 141);
      doc.setLineWidth(2);
      doc.line(MARGIN, y - 10, MARGIN + 24, y - 10);
      writeWrapped(text, 14, { bold: true, color: [255, 77, 141], gap: 6 });
    };

    const bullets = (items: string[]) => {
      for (const it of items) writeWrapped(`•  ${it}`, 10.5, { gap: 2 });
    };

    const a = analysis;

    // Title
    writeWrapped("PeakMinds Candidate Review Report", 20, { bold: true, gap: 2 });
    writeWrapped(new Date().toLocaleDateString(), 9, { color: [140, 140, 140], gap: 10 });

    // Score + verdict
    writeWrapped(`Overall Match Score: ${a.overall_match_score} / 100`, 15, { bold: true, gap: 2 });
    writeWrapped(`Verdict: ${a.recruiter_perspective.verdict}`, 11, { color: [90, 90, 90], gap: 8 });

    // Summary
    heading("Analysis Summary");
    writeWrapped(a.analysis_summary, 10.5, { gap: 6 });

    // JD profile (if present)
    if (a.jd_profile) {
      const p = a.jd_profile;
      heading("Job Description Profile");
      const line = (label: string, val: string) => { if (val) writeWrapped(`${label}: ${val}`, 10.5); };
      const listLine = (label: string, arr: string[]) => { if (arr?.length) writeWrapped(`${label}: ${arr.join(", ")}`, 10.5); };
      line("Role", p.role_title);
      line("Seniority", p.seniority);
      line("Years required", p.years_required);
      listLine("Technical skills", p.technical_skills);
      listLine("Tools", p.tools);
      listLine("Frameworks", p.frameworks);
      listLine("Domain knowledge", p.domain_knowledge);
      listLine("Leadership", p.leadership_requirements);
      listLine("Nice to have", p.nice_to_have_skills);
      y += 4;
    }

    // Strengths
    heading("Strengths");
    for (const s of a.strength_analysis) {
      writeWrapped(s.title, 11, { bold: true, gap: 1 });
      writeWrapped(s.description, 10.5, { gap: 5 });
    }

    // Gaps
    heading("Gaps");
    for (const g of a.gap_analysis) {
      writeWrapped(`${g.title}  [${g.severity}]`, 11, { bold: true, gap: 1 });
      writeWrapped(g.description, 10.5, { gap: 5 });
    }

    // Recruiter perspective
    heading("Recruiter Perspective");
    writeWrapped("Positives", 11, { bold: true, gap: 2 });
    bullets(a.recruiter_perspective.positives);
    y += 2;
    writeWrapped("Concerns", 11, { bold: true, gap: 2 });
    bullets(a.recruiter_perspective.concerns);

    // Roadmap
    heading("Improvement Roadmap");
    writeWrapped("Immediate", 11, { bold: true, gap: 2 });
    bullets(a.improvement_roadmap.immediate);
    y += 2;
    writeWrapped("7-Day Plan", 11, { bold: true, gap: 2 });
    bullets(a.improvement_roadmap.seven_day);
    y += 2;
    writeWrapped("30-Day Plan", 11, { bold: true, gap: 2 });
    bullets(a.improvement_roadmap.thirty_day);

    doc.save("peakminds-candidate-review.pdf");
  } catch {
    // PDF generation failed — fall back to Markdown export
    downloadMarkdown(analysis);
  }
}

// ── Analysis sections ─────────────────────────────────────────────────────────

function SectionHeader({ eyebrow, heading, sub }: { eyebrow: string; heading: string; sub?: string }) {
  return (
    <div>
      <p className="text-[12.5px] font-semibold uppercase tracking-[0.14em] text-accent">{eyebrow}</p>
      <h2 className="mt-2 text-4xl font-bold leading-tight text-foreground">{heading}</h2>
      {sub && <p className="mt-2 max-w-2xl text-lg leading-8 text-foreground/60">{sub}</p>}
    </div>
  );
}

function StrengthCard({ item }: { item: StrengthItem }) {
  return (
    <div className="flex gap-4 rounded-card border border-border bg-surface/50 p-6">
      <span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-accent/15">
        <svg width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="var(--color-accent)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
          <polyline points="2 6.5 4.5 9 10 3" />
        </svg>
      </span>
      <div>
        <p className="text-xl font-semibold text-foreground">{item.title}</p>
        <p className="mt-1.5 text-base leading-7 text-foreground/65">{item.description}</p>
      </div>
    </div>
  );
}

function GapCard({ item }: { item: GapItem }) {
  return (
    <div className="flex gap-4 rounded-card border border-border bg-surface/50 p-6">
      <span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-surface-elevated">
        <svg width="11" height="11" viewBox="0 0 12 12" fill="none" aria-hidden="true">
          <path d="M6 2L11 10H1L6 2Z" stroke="var(--color-subtle)" strokeWidth="1.5" strokeLinejoin="round" />
          <line x1="6" y1="5.5" x2="6" y2="7.5" stroke="var(--color-subtle)" strokeWidth="1.5" strokeLinecap="round" />
          <circle cx="6" cy="9" r="0.6" fill="var(--color-subtle)" />
        </svg>
      </span>
      <div>
        <div className="flex flex-wrap items-center gap-2">
          <p className="text-xl font-semibold text-foreground">{item.title}</p>
          <span className={["rounded-full px-2 py-0.5 text-[11px] font-semibold uppercase tracking-wide", severityClass(item.severity)].join(" ")}>
            {item.severity}
          </span>
        </div>
        <p className="mt-1.5 text-base leading-7 text-foreground/65">{item.description}</p>
      </div>
    </div>
  );
}

function ImprovementColumn({ title, timeLabel, items, accent }: {
  title: string; timeLabel: string; items: string[]; accent?: boolean;
}) {
  return (
    <div className="flex flex-col rounded-card border border-border bg-surface/50 p-6 lg:p-7">
      <p className={["text-[12px] font-semibold uppercase tracking-[0.13em]", accent ? "text-accent" : "text-muted"].join(" ")}>
        {timeLabel}
      </p>
      <p className="mt-1 text-2xl font-semibold text-foreground mb-5">{title}</p>
      <ul className="flex flex-col gap-3.5">
        {items.map((item, i) => (
          <li key={i} className="flex gap-3">
            <span className={["mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full text-[11px] font-bold tabular-nums", accent ? "bg-accent/15 text-accent" : "bg-surface-elevated text-muted"].join(" ")}>
              {i + 1}
            </span>
            <p className="text-base leading-7 text-foreground/75">{item}</p>
          </li>
        ))}
      </ul>
    </div>
  );
}

function AnalysisReport({ data, isSample }: { data: AnalysisOutput; isSample: boolean }) {
  const { overall_match_score: score, analysis_summary, strength_analysis, gap_analysis, recruiter_perspective: rp, improvement_roadmap: ir } = data;

  return (
    <div className="flex flex-col gap-16 lg:gap-20">
      {isSample && (
        <div className="flex items-center gap-3 rounded-xl border border-border bg-surface/40 px-5 py-3.5">
          <span className="flex h-2 w-2 shrink-0 rounded-full bg-accent/70" />
          <p className="text-[13.5px] font-medium text-muted">
            Sample Report — Upload a Job Description and Resume above to see your personalised analysis.
          </p>
        </div>
      )}

      {/* Match Score + Summary */}
      <section aria-label="Overall match score and summary">
        <div className="flex flex-col items-center gap-8 text-center lg:flex-row lg:items-start lg:gap-14 lg:text-left">
          <div className="shrink-0 flex flex-col items-center gap-4">
            <ScoreRing score={score} />
            <p className="text-[13px] font-semibold uppercase tracking-[0.13em] text-muted">
              Overall Match Score
            </p>
          </div>
          <div className="flex flex-col justify-center">
            <p className="text-[12.5px] font-semibold uppercase tracking-[0.14em] text-accent">Analysis Summary</p>
            <h2 className="mt-2 text-4xl font-bold leading-tight text-foreground">{rp.verdict}</h2>
            <p className="mt-4 text-lg leading-8 text-foreground/70 max-w-2xl">{analysis_summary}</p>
            {!isSample && (
              <button
                onClick={() => { void downloadReport(data); }}
                className="mt-6 self-start btn btn-sm btn-secondary flex items-center gap-2"
              >
                <DownloadIcon />
                Download Report (PDF)
              </button>
            )}
          </div>
        </div>
      </section>

      {/* Strengths */}
      {strength_analysis.length > 0 && (
        <section aria-label="Strength analysis">
          <SectionHeader
            eyebrow="Strength Analysis"
            heading="Your Strongest Signals"
            sub="Evidence-backed strengths derived directly from your resume, matched to the job description."
          />
          <div className="mt-10 grid grid-cols-1 gap-4 lg:grid-cols-2">
            {strength_analysis.map((s, i) => <StrengthCard key={i} item={s} />)}
          </div>
        </section>
      )}

      {/* Gaps */}
      {gap_analysis.length > 0 && (
        <section aria-label="Gap analysis">
          <SectionHeader
            eyebrow="Gap Analysis"
            heading="What Recruiters May Not See"
            sub="Signals absent from your resume relative to the job description — and why each one matters."
          />
          <div className="mt-10 grid grid-cols-1 gap-4 lg:grid-cols-2">
            {gap_analysis.map((g, i) => <GapCard key={i} item={g} />)}
          </div>
        </section>
      )}

      {/* Recruiter Perspective */}
      <section aria-label="Recruiter perspective" role="region">
        <SectionHeader
          eyebrow="Recruiter Perspective"
          heading="How Recruiters Will View This Resume"
          sub="PeakMinds applies the same evaluation lens used to shortlist from 100,000 candidates."
        />
        <div className="mt-10 overflow-hidden rounded-card border border-border bg-surface/60">
          <div className="flex flex-wrap items-center justify-between gap-4 border-b border-border px-7 py-5">
            <p className="text-base text-muted">Overall assessment</p>
            <span className={["rounded-full px-4 py-1.5 text-[14px] font-semibold", verdictBadgeClass(rp.verdict)].join(" ")}>
              {rp.verdict}
            </span>
          </div>
          <div className="grid grid-cols-1 divide-y divide-border lg:grid-cols-2 lg:divide-x lg:divide-y-0">
            <div className="px-7 py-6">
              <p className="mb-4 text-[13px] font-semibold uppercase tracking-[0.12em] text-accent">Positive observations</p>
              <ul className="flex flex-col gap-3">
                {rp.positives.map((p, i) => (
                  <li key={i} className="flex gap-3 text-base leading-7 text-foreground/75">
                    <span className="mt-1.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-accent/12">
                      <svg width="10" height="10" viewBox="0 0 12 12" fill="none" stroke="var(--color-accent)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                        <polyline points="2 6.5 4.5 9 10 3" />
                      </svg>
                    </span>
                    {p}
                  </li>
                ))}
              </ul>
            </div>
            <div className="px-7 py-6">
              <p className="mb-4 text-[13px] font-semibold uppercase tracking-[0.12em] text-muted">Recruiter concerns</p>
              <ul className="flex flex-col gap-3">
                {rp.concerns.map((c, i) => (
                  <li key={i} className="flex gap-3 text-base leading-7 text-foreground/75">
                    <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-muted/50" aria-hidden="true" />
                    {c}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* Roadmap */}
      <section aria-label="Improvement roadmap">
        <SectionHeader
          eyebrow="Improvement Roadmap"
          heading="How To Become More Competitive"
          sub="Prioritised, specific improvements — from immediate actions to 30-day goals."
        />
        <div className="mt-10 grid grid-cols-1 gap-4 lg:grid-cols-3">
          <ImprovementColumn title="Act Now" timeLabel="Immediate" items={ir.immediate} accent />
          <ImprovementColumn title="This Week" timeLabel="7-Day Plan" items={ir.seven_day} />
          <ImprovementColumn title="This Month" timeLabel="30-Day Plan" items={ir.thirty_day} />
        </div>
      </section>
    </div>
  );
}

// ── Main component ────────────────────────────────────────────────────────────

export default function CandidateReviewClient() {
  // JD state
  const [jdState, setJdState] = useState<UploadState>("idle");
  const [jdText, setJdText] = useState("");
  const [jdFilename, setJdFilename] = useState("");
  const [jdError, setJdError] = useState("");
  const [jdPaste, setJdPaste] = useState("");

  // Resume state
  const [resumeState, setResumeState] = useState<UploadState>("idle");
  const [resumeText, setResumeText] = useState("");
  const [resumeFilename, setResumeFilename] = useState("");
  const [resumeError, setResumeError] = useState("");
  const [resumePaste, setResumePaste] = useState("");

  // Analysis state
  const [analyzing, setAnalyzing] = useState(false);
  const [analysis, setAnalysis] = useState<AnalysisOutput | null>(null);
  const [analysisError, setAnalysisError] = useState("");

  const resultsRef = useRef<HTMLDivElement>(null);

  const bothReady = jdState === "ready" && resumeState === "ready";

  // ── Handlers ────────────────────────────────────────────────────────────────

  async function handleJdFile(file: File) {
    setJdFilename(file.name);
    setJdError("");
    setJdState("uploading");
    try {
      // Brief uploading phase before the heavy extraction work begins.
      await nextFrame();
      setJdState("extracting");
      const { text } = await extractFromFile(file);
      setJdText(text);
      setJdState("ready");
    } catch (err) {
      setJdError(err instanceof ExtractionError ? err.message : "Extraction failed. Please paste your content instead.");
      setJdState("error");
    }
  }

  async function handleResumeFile(file: File) {
    setResumeFilename(file.name);
    setResumeError("");
    setResumeState("uploading");
    try {
      await nextFrame();
      setResumeState("extracting");
      const { text } = await extractFromFile(file);
      setResumeText(text);
      setResumeState("ready");
    } catch (err) {
      setResumeError(err instanceof ExtractionError ? err.message : "Extraction failed. Please paste your content instead.");
      setResumeState("error");
    }
  }

  function handleJdPaste() {
    const t = jdPaste.trim();
    if (t.length < 30) return;
    setJdText(t);
    setJdFilename("Pasted content");
    setJdState("ready");
    setJdError("");
  }

  function handleResumePaste() {
    const t = resumePaste.trim();
    if (t.length < 30) return;
    setResumeText(t);
    setResumeFilename("Pasted content");
    setResumeState("ready");
    setResumeError("");
  }

  async function handleAnalyze() {
    setAnalyzing(true);
    setAnalysisError("");
    try {
      const res = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ jd: jdText, resume: resumeText }),
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error((body as { error?: string }).error ?? "Analysis failed.");
      }
      const data = (await res.json()) as AnalysisOutput;
      setAnalysis(data);
      setTimeout(() => resultsRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 80);
    } catch (err) {
      setAnalysisError(err instanceof Error ? err.message : "Analysis failed. Please try again.");
    } finally {
      setAnalyzing(false);
    }
  }

  function handleReset() {
    setJdState("idle"); setJdText(""); setJdFilename(""); setJdError(""); setJdPaste("");
    setResumeState("idle"); setResumeText(""); setResumeFilename(""); setResumeError(""); setResumePaste("");
    setAnalysis(null); setAnalysisError("");
  }

  const displayAnalysis = analysis ?? SAMPLE_ANALYSIS;
  const isSample = analysis === null;

  // ── Render ──────────────────────────────────────────────────────────────────

  return (
    <div className="min-h-screen bg-background text-foreground">

      {/* ── Hero ──────────────────────────────────────────────────────────── */}
      <header className="relative overflow-hidden border-b border-border">
        <div
          className="pointer-events-none absolute -top-1/3 left-1/2 -translate-x-1/2 w-[60vw] max-w-[700px] aspect-square rounded-full blur-[200px]"
          style={{ backgroundColor: "rgba(255,77,141,0.05)" }}
          aria-hidden="true"
        />
        <div className="relative container-page pt-32 pb-16 lg:pt-36 lg:pb-20">
          <Link href="/" className="group inline-flex items-center gap-2 text-[14px] font-medium text-muted hover:text-foreground transition-colors duration-150 mb-8">
            <BackArrow />
            Back to PeakMinds
          </Link>
          <p className="text-[13px] font-semibold uppercase tracking-[0.14em] text-accent">
            Candidate Intelligence
          </p>
          <h1 className="mt-4 text-5xl font-bold leading-tight lg:text-[60px]">
            See How PeakMinds
            <br />
            <span className="text-gradient-accent">Evaluates You.</span>
          </h1>
          <p className="mt-5 max-w-[640px] text-xl leading-8 text-foreground/65">
            Upload a job description and your resume. Receive the same evidence-based
            analysis used inside the PeakMinds Talent Intelligence Platform.
          </p>

          {/* ── Two upload cards ─────────────────────────────────────────── */}
          <div className="mt-10 grid grid-cols-1 gap-4 sm:grid-cols-2 items-stretch">
            <UploadCard
              title="Job Description"
              description="Upload or paste the job description you're targeting."
              state={jdState}
              filename={jdFilename}
              error={jdError}
              pasteValue={jdPaste}
              onFile={handleJdFile}
              onPasteChange={setJdPaste}
              onPasteSubmit={handleJdPaste}
              onReset={() => { setJdState("idle"); setJdText(""); setJdFilename(""); setJdError(""); setJdPaste(""); }}
            />
            <UploadCard
              title="Your Resume"
              description="Upload or paste your resume for evaluation."
              state={resumeState}
              filename={resumeFilename}
              error={resumeError}
              pasteValue={resumePaste}
              onFile={handleResumeFile}
              onPasteChange={setResumePaste}
              onPasteSubmit={handleResumePaste}
              onReset={() => { setResumeState("idle"); setResumeText(""); setResumeFilename(""); setResumeError(""); setResumePaste(""); }}
            />
          </div>

          {/* ── Analyze button ────────────────────────────────────────────── */}
          <div className="mt-6 flex flex-col gap-3">
            {bothReady && !analyzing && (
              <button
                onClick={handleAnalyze}
                className="self-start btn btn-md btn-primary px-8"
              >
                Analyze Match
              </button>
            )}
            {analyzing && (
              <div className="flex items-center gap-3 self-start rounded-card border border-border bg-surface/60 px-6 py-4">
                <SpinnerIcon />
                <div>
                  <p className="text-[15px] font-semibold text-foreground">Analyzing…</p>
                  <p className="mt-0.5 text-[13px] text-muted">Comparing resume signals against JD requirements</p>
                </div>
              </div>
            )}
            {analysisError && (
              <div className="rounded-xl border border-red-500/25 bg-red-500/[0.06] px-5 py-4">
                <p className="text-[13.5px] text-red-400">{analysisError}</p>
              </div>
            )}
            {analysis && (
              <button onClick={handleReset} className="self-start text-[13px] font-medium text-muted hover:text-foreground transition-colors">
                ← Start over
              </button>
            )}
          </div>
        </div>
      </header>

      {/* ── Analysis report ────────────────────────────────────────────────── */}
      <div ref={resultsRef} className="container-page py-16 lg:py-24">
        <AnalysisReport data={displayAnalysis} isSample={isSample} />
      </div>

      {/* ── CTA ───────────────────────────────────────────────────────────── */}
      <section className="border-t border-border" aria-label="Call to action">
        <div className="container-page py-16 text-center lg:py-20">
          <h2 className="text-4xl font-bold leading-tight text-foreground">
            Ready to see how recruiters evaluate you?
          </h2>
          <p className="mx-auto mt-4 max-w-md text-xl leading-8 text-muted">
            Upload a job description and your resume to receive a complete PeakMinds intelligence report.
          </p>
          <div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row">
            <button
              onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}
              className="btn btn-md btn-primary px-7"
            >
              Upload Documents
            </button>
            <Link href="/top-100" className="btn btn-md btn-secondary px-7">
              View Top 100 Rankings
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}

// ── Icons ─────────────────────────────────────────────────────────────────────

function BackArrow() {
  return (
    <svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true" className="transition-transform duration-150 group-hover:-translate-x-0.5">
      <path d="M11 7H3M6.5 3.5L3 7l3.5 3.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}
